import SLL
import stack

s = stack.Stack()
print(s.GetValues())
s.Push(2)
print(s.GetValues())
print(s.GetCount(), " Items in the stack")
print("Pop: ", s.Pop())
print(s.GetCount(), " Items in the stack")
print(s.GetValues())
s.Push(2)
s.Push(1)
s.Push(3)
s.Push(9)
print(s.GetValues())
print("Pop: ", s.Pop())
print(s.GetCount(), " Items in the stack")
print(s.GetValues())

#l = ItemList()

#print("Stack")
#l.stackPush(0)
#l.printList()
#l.stackPush(20)
#l.printList()
#print("Popped: ", l.stackPop())
#l.printList()
#l.stackPush(9)
#l.printList()
#l.stackPush("test")
#l.printList()
#print("Peeked: ", l.stackPeek())
