import SLL
import stack
import queue

print("Stack Demo")
s = stack.Stack()
print(s.GetValues())
s.Push(2)
print(s.GetValues())
print(s.GetCount(), " Items in the stack")
print("Pop: ", s.Pop())
print(s.GetCount(), " Items in the stack")
print(s.GetValues())
print("Push 2,1,3,9")
s.Push(2)
s.Push(1)
s.Push(3)
s.Push(9)
print(s.GetValues())
print("Peek: ", s.Peek())
print("Pop: ", s.Pop())
print(s.GetCount(), " Items in the stack")
print(s.GetValues())

print()
print("Queue Demo")
q = queue.Queue()
print(q.GetValues())
q.Enqueue(2)
print(q.GetValues())
print(q.GetCount(), " Items in the stack")
print("Dequeue: ", q.Dequeue())
print(q.GetCount(), " Items in the stack")
print(q.GetValues())
print("Peek: ", q.Peek())
print("Queue 2,1,3,9")
q.Enqueue(2)
q.Enqueue(1)
q.Enqueue(3)
print(q.GetValues())
q.Enqueue(9)
print(q.GetValues())
print(q.GetCount(), " Items in the queue")
print("Peek: ", q.Peek())
print("Dequeue: ", q.Dequeue())
print(q.GetCount(), " Items in the queue")
print(q.GetValues())


